### ISSUE TITLE
Animated node with ID 2 already exists

### ISSUE THREAD

**Issue by Billmike** [alexZajac/react-native-skeleton-content-nonexpo#15]
**Describe the bug**
I installed the `react-native-skeleton-content-nonexpo` library, and after following the example code in the documentation, I got the error `Animated node with ID 2 already exists`

**Screenshots**
<img width="314" alt="Screenshot 2020-06-11 at 16 54 33" src="https://user-images.githubusercontent.com/24798364/84408779-76ba7800-ac04-11ea-87f5-2daf66f08d17.png">

**Additional context**
I'm running React native v0.62.2 and react-native-skeleton-content-nonexpo v1.0.8

**Comment by alexZajac** [comment]
Hey @Billmike ! 
I never encountered that one, but this one seems similar https://github.com/software-mansion/react-native-reanimated/issues/742

Anyways, I am planning to have a deeper testing session this weekend, and I will probably release another patch. 

Will keep you updated :smile:

**Comment by Billmike** [comment]
Alright @alexZajac I look forward to your updates!

**Comment by alexZajac** [comment]
Hye @Billmike 
I published an updated version of the package this morning. 
Nevertheless, did you try the fix in the other repo? 

Can you also provide a playground (snack or anything else) to test?

**Comment by Billmike** [comment]
@alexZajac I don't understand the suggested fix. I just updated to the latest version you released and it's still the same error.

**Comment by Billmike** [comment]
@alexZajac I tried running it on a separate repo, and it works fine. Not sure what the problem is.

**Comment by alexZajac** [comment]
Okay, well that's a good start, if it's fine in another repo then it must be something related to dependencies in yours specifically. I can try testing it with an emulator if you provide me some code. Closing it for now

**Comment by auggustus6** [comment]
The same problem happens to me

**Comment by bguaitanele** [comment]
Same here!

**Comment by alexZajac** [comment]
Hey guys, can you provide an environment for me to test? I can't reproduce it

**Comment by Nandolinhares** [comment]
Hey, I was having the same problem! I solved changing NPM to Yarn. Just deleted the project from my PC. After that, I cloned and used the command "yarn install". That was the solution

**Comment by PiPoutch** [comment]
In my case, the problem was mismatching versions of react-native-reanimated. Your package uses the latest, so the problem wasn't coming from it!

**Comment by Billmike** [comment]
@PiPoutch What versions of react-native-reanimated did you upgrade to?

**Comment by PiPoutch** [comment]
1.9.0

**Comment by Billmike** [comment]
That's the version I was on when I got the above error

**Comment by Billmike** [comment]
Anyone found a fix that works for them yet??

**Comment by gregdburns** [comment]
FWIW: I'm getting this error after upgrading from Expo V36 to Expo V37.  I tried upgrading react-native-reanimated to 1.9.0 but that didn't work.

**Comment by osikes** [comment]
Running to exact same issue.

**Comment by osikes** [comment]
Updating my previous comment ... android issue indeed ended up being I had both references to reanimated 1.8.x and 1.9.x. Getting everything to 1.9.x resolved issue. Now it's working awesome on android and iOS. Great repo , thanks :)

**Comment by alexZajac** [comment]
Okay, from previous answers it seems like a dependency/versioning issue with `react-native-reanimated`, so closing for now as the previous answers give enough context to solve it.

**Comment by Billmike** [comment]
@osikes When you say `getting everything to 1.9.x resolved issue`, can you elaborate on that? What is the source of the versioning issue, as it's unclear to me since I have only one version of react-native-reanimated installed and I keep getting the same error? @alexZajac

**Comment by gregdburns** [comment]
@osikes for me, there were some dependencies that had a different version, and despite using NPM, had a conflict.  I believe this only happens when those dependencies are loaded in your app and somehow need to communicate with each other.  For me, it was my version of Expo and another library that used react-native-reanimated.

The way I investigated the libraries that were the issue was by searching my node_modules folder for react-native-reanimated and going from there.  Hope that helps!

**Comment by osikes** [comment]
> @osikes When you say `getting everything to 1.9.x resolved issue`, can you elaborate on that? What is the source of the versioning issue, as it's unclear to me since I have only one version of react-native-reanimated installed and I keep getting the same error? @alexZajac

Sure @Billmike  . For me it was as simple as my package.json had a reference to "react-native-reanimated": "^1.8.0", which I needed to change to 1.9.0.

Now if you have various dependencies that then themselves reference different versions of 'react-native-reanimated'.. you're probably in for a more difficult time 😞  . And will either have to request author of those libraries to update or fork them yourself.

**Comment by Billmike** [comment]
@osikes That seemed to fix my issue. I was on version ^1.8.0. Switching to version 1.9.0, without the ^ fixed that error. I guess there's a clash of versions in libraries using react-native-reanimated as a dependency

**Comment by VKBobyr** [comment]
I'm experiencing the same issue, on version 1.9.0. Here's my package.json:
```json
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "clean": "rm -rf node_modules yarn.lock && yarn install"
  },
  "dependencies": {
    "@expo/vector-icons": "^10.0.0",
    "axios": "^0.19.2",
    "expo": "^38.0.0",
    "expo-mail-composer": "~8.2.1",
    "expo-splash-screen": "^0.3.1",
    "firebase": "7.9.0",
    "lodash": "^4.17.19",
    "material-colors": "^1.2.6",
    "native-base": "^2.13.13",
    "prop-types": ">=15.5.10",
    "react": "16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
    "react-native-cheerio": "^1.0.0-rc.4",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-keyboard-aware-scrollview": "^2.1.0",
    "react-native-modal": "^11.5.6",
    "react-native-phone-call": "^1.0.9",
    "react-native-reanimated": "~1.9.0",
    "react-native-safe-area-context": "~3.0.7",
    "react-native-screens": "~2.9.0",
    "react-native-skeleton-content": "^1.0.18",
    "react-navigation": "^4.4.0",
    "react-navigation-drawer": "^2.5.0",
    "typescript": "~3.9.5",
    "typescript-eslint": "^0.0.1-alpha.0",
    "valid-url": "^1.0.9"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "@typescript-eslint/eslint-plugin": "^3.6.1",
    "@typescript-eslint/parser": "^3.6.1",
    "eslint": "7.4.0",
    "eslint-config-airbnb": "18.2.0",
    "eslint-plugin-import": "2.22.0",
    "eslint-plugin-jsx-a11y": "6.3.1",
    "eslint-plugin-react": "7.20.3",
    "eslint-plugin-react-hooks": "4.0.6"
  },
  "private": true
}

```

**Comment by anastely** [comment]
This Lib did not work with reanimated 2?
because I got the same issue, in my case I have reanimated 2!

**Comment by Syed-Musthafa** [comment]
I tried all the methods but its doesn't work for me
